version: '3.5'

services:
  app:
    build: .
    image: rails6
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - '.:/usr/src/app'
      - rails5-usrlocal:/usr/local/

volumes:
  rails6-usrlocal:

networks:
  local:
  
  
