# database container
db:
  image: docker.io/mysql
  ports:
    - "2222:2222"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    
# application container
app:
  image: docker.io/tomcat
  ports:
    - "8080:8080"

# web container
web:
  image: docker.io/nginx
  posts:
    - "3606:3606"