FROM ubuntu:16.04

RUN apt update
RUN apt install -y cron

COPY task.sh /usr/local/bin/
COPY cron /etc/cron.d/
RUN chmod 0614 /etc/cron.d/cron-

CMD ["cron", "-f"]

// MYSQL Data Volume
FROM busybox

VOLUME /var/lib/mysql

CMD ["bin/true"]



